export const fileIcons = {
  js: 'mdi-language-javascript text-teal',
  md: 'mdi-language-markdown text-teal',
  json: 'mdi-code-json text-teal',
  xls: 'mdi-file-excel text-green',
  xlsx: 'mdi-file-excel text-green',
  xlsm: 'mdi-file-excel text-green',
  xlsb: 'mdi-file-excel text-green',
  xltx: 'mdi-file-excel text-green',
  csv: 'mdi-file-excel text-green',
  jpg: 'mdi-image text-danger',
  jpeg: 'mdi-image text-danger',
  png: 'mdi-image text-danger',
  pdf: 'mdi-file-pdf text-orange',
  mp3: 'mdi-file-music text-purple',
  wav: 'mdi-file-music text-purple',
  aa: 'mdi-file-music text-purple',
  midi: 'mdi-file-music text-purple',
  mdi: 'mdi-file-music text-purple',
  '': 'mdi-file-document text-primary'
}
